spring:
  datasource:
    url: jdbc:mysql://localhost:3062/querydsl?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #query를 이쁘게
       show_sql : true
       format_sql: true

logging.level:
  org.hibernate.SQL: debug    #hibernate가 실행하는 query 들이 logger 로 출력
  #org.hibernate.type: trace  #system.out 으로 출력

server:
  port: 7025